package com;

import com.components.EditorPane;
import com.components.HeaderMenuPane;
import com.components.ProjectFolderPane;
import com.components.TerminalPane;
import com.core.StatsFacade;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;

public class Sandbox {
    // MAIN FRAME UI
    private JPanel mainPanel;

    // HEADER UI
    private JButton fileButton;
    private JButton buildButton;

    // PROJECT PANEL UI
    private JTree projectPane;

    // EDITOR SANDBOX UI
    private JTabbedPane tabPane;

    // TERMINAL UI
    private JTextArea terminalPane;
    private JPanel editorContainer;
    private JTextField statsField;

    // CUSTOM LAYOUT COMPONENTS
    private ProjectFolderPane projectFolderPane;
    private HeaderMenuPane headerMenuPane;
    private EditorPane editorPane;
    private TerminalPane terminalCompPane;

    // MISC
    public final static StatsFacade statsFacade = new StatsFacade();

    public Sandbox() {
        editorPane = new EditorPane(editorContainer, tabPane);
        projectFolderPane = new ProjectFolderPane(projectPane, mainPanel, editorPane);
        headerMenuPane = new HeaderMenuPane(fileButton, buildButton, projectFolderPane);
        terminalCompPane = new TerminalPane(terminalPane);

        projectFolderPane.init();
        headerMenuPane.init();

        statsFacade.setField(statsField);
        fileButton.addMouseListener(new MouseAdapter() {
        });
    }

    public static void main(String[] args) {
        initFrame("Lucid");
    }

    private static void initFrame(String title) {
        JFrame frame = new JFrame(title);
        frame.setContentPane(new Sandbox().mainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    private void SetupProjectPane() {
        projectPane.setModel(null);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(panel1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        projectPane = new JTree();
        projectPane.setBackground(new Color(-3949910));
        projectPane.setForeground(new Color(-1319733));
        panel1.add(projectPane, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, 50), null, 2, false));
        editorContainer = new JPanel();
        editorContainer.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(editorContainer, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        tabPane = new JTabbedPane();
        tabPane.setTabPlacement(1);
        editorContainer.add(tabPane, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        terminalPane = new JTextArea();
        terminalPane.setColumns(0);
        terminalPane.setEditable(false);
        terminalPane.setLineWrap(true);
        terminalPane.setText("");
        terminalPane.setWrapStyleWord(true);
        terminalPane.putClientProperty("caretWidth", new Integer(2));
        editorContainer.add(terminalPane, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(150, 50), null, 0, false));
        statsField = new JTextField();
        statsField.setEditable(false);
        editorContainer.add(statsField, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        mainPanel.add(panel2, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(-1, 50), null, new Dimension(-1, 50), 0, false));
        fileButton = new JButton();
        fileButton.setHorizontalAlignment(0);
        fileButton.setText("File");
        fileButton.setVerticalTextPosition(0);
        panel2.add(fileButton);
        buildButton = new JButton();
        buildButton.setHorizontalAlignment(0);
        buildButton.setHorizontalTextPosition(0);
        buildButton.setText("Build");
        panel2.add(buildButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
