package com;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import com.lucidcore.*;

public class TestApp extends JFrame {

    private JButton saveButton;
    private JPanel panel1;
    private JTree folderPanel;


    public TestApp() {
        final IProjectManager projMgr = new ProjectManager();
        final JFrame frame = this;

        /*saveButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent actionEvent) {
                String projectName = JOptionPane.showInputDialog("Provide Project Name: ");

                JFileChooser chooser = new JFileChooser("f:");
                chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                chooser.setAcceptAllFileFilterUsed(false);

                if (chooser.showOpenDialog(frame) == JFileChooser.APPROVE_OPTION) {
                    try {
                        projMgr.createProject(projectName, chooser.getCurrentDirectory().getAbsolutePath());
                    }
                    catch (Exception e) {
                        JOptionPane.showMessageDialog(frame, "Error creating project: " + e.getMessage());
                    }
                }
                else {
                    System.out.println("No Selection ");
                }
            }
        });*/

        this.setTitle("Test App");
        // this.add(saveButton);

        this.setSize(500, 500);
        this.setVisible(true);
    }

    public static void main(String[] args) {
        new TestApp();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        folderPanel = new JTree();
        panel1.add(folderPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
